name: Hello World

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  hello:
    runs-on: [self-hosted, talos]
    steps:
      - name: Hello World
        run: echo "Hello World"
